### ISSUE TITLE
FindFirstFile Error

### ISSUE THREAD

**Issue by comanche** [idrassi/DirHash#15]
Tried running this command:

```bat
DirHash.exe G:/ blake3 -t E:\dirhash.blake3 -overwrite -sum -threads -nologo -progress -nowait -exclude
```

Go this error: `FindFirstFile failed on "G:\System Volume Information" with error 0x00000005.`

Wondering if there are handling issues in the `System Volume Information` folder.

**Comment by idrassi** [comment]
"`System Volume Information`" is a special folder created by Windows and which cannot be accessed by users. The error code 0x00000005 means "Access Denied".
So DirHash cannot access the content of this folder and that's why the operation is aborted.

You can tell DirHash to ignore this system folder by using `-exclude` switch. So the command becomes:

`DirHash.exe G:/ blake3 -t E:\dirhash.blake3 -overwrite -sum -threads -nologo -progress -nowait -exclude "G:\System Volume Information"`
