### ISSUE TITLE
Verification Failing

### ISSUE THREAD

**Issue by comanche** [idrassi/DirHash#22]
I have a used DirHash verify on a drive (361,855 files) with some these issues:

1. I generate a checksum file.
2. I verify the drive using the checksum file.
3. Some files (on the drive) are showing as not found in checksum file.  However, when I manually check the checksum file, they are there.
4. The same files mentioned in the previous step in the checksum file are showing not found on the drive.
5. I've rerun this multiple times with the same result

Steps 3 and 4 contradict each other.

I've run the DirHash checksum file with other similar applications that they pass verification.  Only DirHash is having issues with it's own checksum file.

The confusing part is that I attempted to generate a checksum file for a directory with the problem files.  This is only a tiny subset of the files in the checksum file.  The verification passed without issues.

Any ideas?  Could there be issues with

- too many files in the checksum file
- special characters

**Comment by idrassi** [comment]
This is indeed very confusing!
Since DirHash checksum file can be verified with other applications, the issue is in DirHash building of full path for the entries in the checksum and for some of them this full path is not correct, which explains both Step 3 and Step 4.

In order to help me understand the issue:
- Did you generate the checksum file using `-sumRelativePath` switch?
- Are you using full path for the input drive or are you using relative path? I mean do you call DirHash like "`DirHash Z:\ -sum`" or "`DirHash . -sum`"?
- Do you notice anything special about the parent folders of the affected file? like special characters used only there? 
- Is the path of the affected files longer than the other files?

I will also try to re-check the code in case I notice something wrong their.
Thank you for your help.

**Comment by comanche** [comment]
Found out what the issue is.  DirHash is case sensitive.  Fixed the filenames to match and that fixed the issue.
