### ISSUE TITLE
Issue with winget verification for the new release?

### ISSUE THREAD

**Issue by w3lld0ne** [idrassi/DirHash#29]
https://github.com/microsoft/winget-pkgs/pull/110118

It seems like the latest update cannot pass antivirus scan.

**Comment by idrassi** [comment]
This is very strange and in the winget issue it mentions the error `0x80004005` which is not helpful since it translates to "**Unspecified error"** .

I have just run a check using VirusTotal and no issues are found: https://www.virustotal.com/gui/file/d02ecc173f4427c407fa140750021bbfb34124b5af7f3f418b8b8beae543acf8?nocache=1

I will post a message on winget issue to seek information because I don't see anything wrong.

**Comment by w3lld0ne** [comment]
It was a false-positive, thanks for your involvement!
