### ISSUE TITLE
error verifying directory hash

### ISSUE THREAD

**Issue by GuHue** [idrassi/DirHash#4]
When I try to use the "verify" switch after computing a directory hash with result in a file, I get an error message "Failed to parse checksum file...".
But it works if I compute the hash for every file (with the "sum" switch)...but that's not what I need :-)

**Comment by idrassi** [comment]
Indeed, this use case doesn't work because the current implementation of the "verify" switch only handle checksum files case.

I will implement support for simple verification of directory hash and the publish a new version. It doesn't sound complex so I should be able to do this in the coming days.

**Comment by GuHue** [comment]
It would be great. Thanks! (and thanks again for your quick answer)

**Comment by idrassi** [comment]
I have implemented this feature in the commit https://github.com/idrassi/DirHash/commit/b40642e8039d928fb7580c971224aefba429363b

I have published version 1.11 that contains this implementation.

I will close this issue. Feel free to reopen if you encounter any issues.
